config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :items
  root "items#index"
  get "users/mypage"
  resources :users do
    collection do
      get :mypage
      get :record
    end
  end
  resources :line_items do
    member do
      delete :destroy_in_cart
      get :change_qty
    end
  end
  resources :orders
  resources :ratings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    require 'carrierwave/orm/activerecord' #서순 정립, 없으면 에러난대
    mount_uploader :image_url, ImageUploader #post 모델의 image_url이란 column에 내가 올린 파일의 주소를 저장해라.

    belongs_to :user
    has_many :ratings, dependent: :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order(created_at: :desc)
    if current_user.present? && Order.find_by(user_id:current_user, status:0).blank?
      order = Order.new(user_id: current_user.id, status: 0, amount: 0)
      order.save
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @user = @item.user
    if current_user.present?
      order = Order.find_by(user_id: current_user.id, status: 0)
      @line_item = LineItem.find_by(order_id: order.id, item_id: params[:id])
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :quantity, :content, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= form_for(@item) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <br>
  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>
  <br>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <br>
  <div class="field">
    <%= f.label :image_url, 'Image' %>
    <%= f.file_field :image_url %>
  </div>
  <br>
  <div class = "button">
    <%= f.submit 'Post Items!' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>


<div class = "items">
  <% @items.each do |item| %>
    <%= link_to  item do %>
      <div class = "items__item">
        <div class = "items__item-column">
          <%= image_tag(item.image_url.url, :class => "items__item-image")%>
        </div>
        <div class = "items__item-column">
          <div class = "items__item-name">
            <%= item.name %>
          </div>
          <div class = "items__item-content">
            <%= item.content %>
          </div>
          <div class = "items__item-price">
            <%= item.price %>원
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<% if current_user.present? %>
  <%= link_to  new_item_path do%>
  <div id = "post_item">
    <i class="fas fa-plus"></i>
  </div>
  <% end %>
<% end %>



<br>

app/views/items/new.html.erb
<h1>상품 등록하기</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="item-image-frame">
    <%= image_tag @item.image_url.url, :class => "item-image" %>
</div>
<%= link_to  @user do %>
<div class = "item__user">
    <div class = "item__user__avatar-frame">
        <% if @user.avatar.present? %>
          <%= image_tag @user.avatar.url, :class => "item__user__avatar" %>
        <% else %>
          <%= image_tag "/images/profile.jpg", :class => "item__user__avatar" %>
        <% end %>
    </div>
    <div class = "item__user-column">
        <div class = "item__user-name">
            <%= @item.user.name %>
        </div>
        <div class = "item__user-address">
            <%= @item.user.address1 %>
        </div>
    </div>
</div>
<% end %>
<div class="item-column">
    <div class = "item__name">
        <%= @item.name %>
    </div>
    <div class = "item__price">
        <%= @item.price %>원
    </div>
</div>
<div class = "item__quantity">
    남은 수량 : <%= @item.quantity %>개
</div>
<div class = "item__content">
    <%= @item.content %>
</div>
<div class="item__button-tab">
<% if @item.user == current_user %>
    <%= link_to edit_item_path(@item), class: "item__update-button button" do  %>
            수정하기
    <% end %>
    <%= link_to  item_path(@item), method: :delete, class: "item__delete-button button" do %>
            삭제하기
    <% end %>
<% elsif current_user.present? %>
    <% if @line_item.blank? %>
        <%= link_to line_items_path(id: @item.id), method: :post, class: "item__cart-button button", id: "buy" do %>    
            장바구니에 담기
        <% end %>
    <% else %>
        <%= link_to line_item_path(@item), method: :delete, class: "item__cart-button button", id: "dontbuy" do %>    
            장바구니에서 빼기
        <% end %>
    <% end %>
<% end %>
</div>
<div class = "ratings">
    <% if @item.ratings.present? %>
    
    <% else %>
        등록된 평가가 없습니다.
    <% end %>
</div>