config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :items
  root "items#index"
  get "users/mypage"
  resources :users do
    collection do
      get :mypage
      get :record
    end
  end
  resources :line_items do
    member do
      delete :destroy_in_cart
      get :change_qty
    end
  end
  resources :orders
  resources :ratings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
    def index
        @order = Order.find_by(user_id: current_user.id, status: 0)
        @line_items = LineItem.where(order_id: @order.id)
    end

    def create
        @item = Item.find(params[:id])
        line_item = LineItem.new(quantity: 1, amount: @item.price)
        order = Order.find_by(user_id: current_user.id, status: 0)
        line_item.item_id = @item.id
        line_item.order_id = order.id
        line_item.save
        order.update(amount: order.amount + line_item.amount)
        redirect_to item_path(params[:id])
    end

    def destroy
        order = Order.find_by(user_id: current_user.id, status: 0)
        line_item = LineItem.find_by(order_id: order.id, item_id: params[:id])
        order.update(amount: order.amount - line_item.amount)
        line_item.destroy
        redirect_to item_path(params[:id])
    end

    def destroy_in_cart
        line_item = LineItem.find(params[:id])
        order = Order.find_by(user_id: current_user.id, status: 0)
        order.update(amount: order.amount - line_item.amount)
        line_item.destroy
        redirect_to line_items_path
    end

    def change_qty
        @line_item = LineItem.find(params[:id])
        @order = current_user.orders.find_by(status: 0)
        if @line_item
            item = @line_item.item
            if params[:type] == "plus" && @line_item.quantity == item.quantity
                @status = 1
            elsif params[:type] == "minus" && @line_item.quantity == 1
                @status = -1
            else
                @status = 0
                num = (params[:type] == "plus") ? 1 : -1
                @line_item.update(quantity: @line_item.quantity + num)
                @line_item.update(amount: @line_item.quantity * @line_item.item.price)
                @order.update(amount: 0)
                @order.line_items.each do |snatch|
                    @order.update(amount: @order.amount + snatch.amount)
                end
            end
        end
    end

    private

    def line_item_params
        params.require(:line_item).permit(:quantity, :amount)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_line_item.html.erb
<% line_item ||= nil %>
<% if line_item %>
<div class="line_item">
    <%= image_tag item.image_url.url, class: "line_item-image" %>
    <div class="line_item-column">
        <div class = "line_item-name">
            <%= item.name %>
        </div>
        <div class="line_item-content">
            <%= item.content %>
        </div>
    </div>
    <div class="line_item-column">
        <div class="line_item-quantity" id="line_item-quantity-<%=line_item.id%>">
            수량 : <%= line_item.quantity %>개
        </div>
        <div class="line_item-amount" id="line_item-amount-<%=line_item.id%>">
            <%= item.price * line_item.quantity %>원
        </div>
    </div>
</div>
<% end %>

app/views/line_items/change_qty.js.erb
function changeQty() {
    $('#line_item-quantity-<%= @line_item&.id %>').html("수량 : <%= @line_item.quantity %>개");
    $('#line_item-amount-<%= @line_item&.id%>').html("<%= @line_item.  amount %>원");
    $('.buy-tab__amount').html("<%= @order.amount   %>원");
}

if(<%= @status %> == 1) {
    alert("최대 수량입니다.");
}else if(<%= @status %> == -1) {
    alert("최소 수량입니다.")
}else {
    changeQty();
}

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Cart</h1>


    <% if @line_items.blank? %>
        <div class = "no_element">
            장바구니가 비어있습니다.
        </div>
    <% else %>
        <div class = "line_items">
            <% @line_items.each do |line_item| %>
            <% item = line_item.item %>
                <div class="line_item">
                    <%= link_to destroy_in_cart_line_item_path(line_item), class: "line_item__delete-button", method: :delete do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                    <%= image_tag item.image_url.url, class: "line_item-image" %>
                    <div class="line_item-column">
                        <div class = "line_item-name">
                            <%= item.name %>
                        </div>
                        <div class="line_item-content">
                            <%= item.content %>
                        </div>
                    </div>
                    <div class="line_item-column qty_tab">
                        <%= link_to  change_qty_line_item_path(line_item, type: "minus"), class: "line_item-minus", id: "minus-#{line_item.id}", :remote => true do %>
                            -
                        <% end %>
                        <div class="line_item-quantity" id="line_item-quantity-<%=line_item.id%>">
                            수량 : <%= line_item.quantity %>개
                        </div>
                        <%= link_to  change_qty_line_item_path(line_item, type: "plus"), class: "line_item-plus", id: "plus-#{line_item.id}", :remote => true do %>
                            +
                        <% end %>
                        <div class="line_item-amount" id="line_item-amount-<%=line_item.id%>">
                            <%= item.price * line_item.quantity %>원
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="buy-tab">
            <div class="buy-tab__amount">
                <%= @order.amount %>원
            </div>
            <%= link_to edit_order_path(@order),class: "buy-tab__buy-button" do %>
                구매하기
            <% end %>
        </div>
    <% end %>




<br>