config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :items
  root "items#index"
  get "users/mypage"
  resources :users do
    collection do
      get :mypage
      get :record
    end
  end
  resources :line_items do
    member do
      delete :destroy_in_cart
      get :change_qty
    end
  end
  resources :orders
  resources :ratings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cucumber</title>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag('application') %>
    <script src="https://kit.fontawesome.com/4891fd3790.js" crossorigin="anonymous"></script>


  

    <link rel="stylesheet" href="/css/items/index.css" />
    <link rel="stylesheet" href="/css/nav.css" />
    <link rel="stylesheet" href="/css/items/show.css" />
    <link rel="stylesheet" href="/css/users/mypage.css" />
    <link rel="stylesheet" href="/css/line_items/index.css" />
    <link rel="stylesheet" href="/css/order.css" />
    <style>
      a {
        text-decoration : none;
      }
      header a {
        color : white;
      }
      * {
        box-sizing : border-box;
      }
      html, body, main {
        width : 100%;
        margin : 0;
      }
      main {
        padding-top: 109.63px;
        padding-bottom: 60.99px;
        padding-left:33px;
        padding-right:33px;
      }
      header {
        position : fixed;
        width : 100%;
        left: 0;
        top : 0;
        padding-top : 3px;
        padding-right : 4px;
        background-color : #38970A;
        display :flex;
        justify-content : space-between;
        align-items : center;
        color : white;
      }
      .header-column {
        margin-left : 5px;
        display :flex;
      }
      #logo {
        width:165px;
        height:70px;
      }
      input[type="submit"] {
        background-color: #38970A;
        color : white;
        font-size: 20px;
        display : flex;
        justify-content: center;
        align-items: center;
        border: 0.5px solid black;
      }

      .no_element {
        position: absolute;
        width: 100%;
        top :50%;
        text-align : center;
        font-size : 50px;
        color : #2ed573;
      }
    </style>
  </head>

  <body>
  <header>
    <div class = "header-column back_button">
      <%= link_to :back do %>
      <i class="fas fa-chevron-left"></i>Back
      <% end %>
    </div>
    <div class = "header-column">
      <%= link_to root_path do %>
      <img src="/images/cucumber.jpg" id="logo">
      <% end %>
    </div>
  <% if user_signed_in? %>
    <div class = "header-column">
      <div class = "header-column">
        <%= current_user.name %>님 어서오고~
      </div>
      <div class = "header-column">
        <%= link_to '로그아웃', destroy_user_session_path, method: :delete %>
      </div>
    </div>
    <% else %>
    <div class = "header-column">
      <div class = "header-column">
        <%= link_to '회원가입', new_user_registration_path %>
      </div>
      <div class = "header-column">
        <%= link_to '로그인', new_user_session_path%>
      </div>
    </div>
    <% end %>
  </header>
  <main>
    <%= yield %>
  </main>
  <nav class ="nav">
    <ul class = "nav_list">
      <%= link_to items_path  do%>
      <li class="nav_list_item">
        <i class="fas fa-store"></i>
      </li>
      <% end %>
      <% if current_user.present? %>
        <li class="nav_list_item">
          <i class="fas fa-city"></i>
        </li>
        <li class="nav_list_item">
          <i class="fas fa-map-marker-alt"></i>
        </li>
        <%= link_to line_items_path do %>
          <li class="nav_list_item">
            <i class="fas fa-shopping-cart"></i>
          </li>
        <% end %>
        <%= link_to  users_mypage_path do %>
          <li class="nav_list_item">
            <i class="fas fa-user"></i>
          </li>
        <% end %>
      <% else %>
        <%= link_to  new_user_session_path do %>
          <li class="nav_list_item">
            <i class="fas fa-city"></i>
          </li>
        <% end %>
        <%= link_to  new_user_session_path do %>
          <li class="nav_list_item">
            <i class="fas fa-map-marker-alt"></i>
          </li>
        <% end %>
        <%= link_to  new_user_session_path do %>
          <li class="nav_list_item">
            <i class="fas fa-shopping-cart"></i>
          </li>
        <% end %>
        <%= link_to  new_user_session_path do %>
          <li class="nav_list_item">
            <i class="fas fa-user"></i>
          </li>
        <% end %>
      <% end %>
      
    </ul>
  </nav>
  </body>
</html>